package team.bridgers.backend.domain.user.domain;

public enum Interest {
    IT_SOFTWARE_DEVELOPMENT,
    DESIGN_CONTENT_CREATION,
    MANAGEMENT_OFFICE_ACCOUNTING,
    MARKETING_PROMOTION_SALES,
    RESEARCH_TECHNOLOGY_ENGINEERING,
    EDUCATION_SERVICE_SOCIAL_WELFARE,
    PRODUCTION_MANUFACTURING_CONSTRUCTION,
    MEDICAL_HEALTH_ENVIRONMENT,
    FINANCE_INSURANCE_LEGAL,
    OTHERS
}
